### ISSUE TITLE
Autobahn links not working

### ISSUE THREAD

**Issue by Paxa** [imanel/websocket-ruby#24]
404

**Comment by imanel** [comment]
Thanks - should be fixed now!

**Comment by Paxa** [comment]
Almost (`Heroku | No such app`)

**Comment by imanel** [comment]
Please wait for dns to refresh and then try to confirm. It may take couple
hours.
W dniu niedz., 24.04.2016 o 17:50 Pavel <notifications@github.com>
napisał(a):
