### ISSUE TITLE
Using client certificates & other SSL features

### ISSUE THREAD

**Issue by ljckennedy** [imanel/websocket-ruby#29]
Is it possible to use client certificates?  I am connecting to a server that requires certificate based authentication.  

In my non-websockets code (which used HTTPClient) I can make calls like this:

client.ssl_config.set_trust_ca(@root)
client.ssl_config.set_client_cert_file(@cert, @key)
client.ssl_config.verify_mode = OpenSSL::SSL::VERIFY_PEER

i.e, set the root, set the client cert and set the verification.  I can't find how to do any of this with your gem.

If it is possible, can you point me to an example?  If I need to to this as a standard https connection then upgrade it, can you point me to an example of this?

Thanks.

**Comment by imanel** [comment]
This library is responsible for handling WebSocket protocol, while SSL part is more connected with server/client implementation you will be using to handle WS. Example implementation for EventMachine [client](https://github.com/imanel/websocket-eventmachine-client/blob/master/lib/websocket/eventmachine/client.rb#L86) and [server](https://github.com/imanel/websocket-eventmachine-server/blob/master/lib/websocket/eventmachine/server.rb#L52). If you need some other implementation then let me know and I can help with finding best solution.

**Comment by ljckennedy** [comment]
I found a solution (at least so far) with websocket-client-simple which I believe sits on top of your gem.  It didn't have the support either, but I was able to patch it fairly easily to add this.  Hopefully they will accept my change, but for now I am working with my own copy.

I tried eventmachine, based implementations but they didn't seem to fit what I was trying to do very well.

**Comment by imanel** [comment]
Great to hear. I will close this for now - if you have more questions then please don't hesitate to open new issue.
