### ISSUE TITLE
TEENY release should not bump the required Ruby version

### ISSUE THREAD

**Issue by BanzaiMan** [imanel/websocket-ruby#38]
I see that 1.2.7 bumped the required Ruby version to `>= 2.3`, up from 1.2.5 in `>= 2.0`. This is surprising and difficult to cope with.

What was the rationale for such a change?

**Comment by imanel** [comment]
I completely forgot about it. Let me verify if I'm still compatible with 2.0 and bump version.

**Comment by imanel** [comment]
You can track progress in https://github.com/imanel/websocket-ruby/pull/39

**Comment by imanel** [comment]
Just released 1.2.8, should fix this problem.

**Comment by BanzaiMan** [comment]
@imanel Thank you!
