### ISSUE TITLE
Some bytes not sent correctly

### ISSUE THREAD

**Issue by andresespinosapc** [imanel/websocket-ruby#42]
When I send "\xc2" in the server I get "\xef\xbf\xbd". It doesn't happen to me with any other hex code as far as I know.

What could the problem be?

**Comment by imanel** [comment]
That's weird - "\xef\xbf\xbd" is UTF-8, which should not happen. What client and server are you using?

**Comment by imanel** [comment]
Closing due to no feedback. Please reopen if it's still valid.
